here we are going to do

converting sentences into **vocabulary**

converting into one hot encoding **one->one hot encoding**

adjusting the size of sentences using padding **padding-> post padding and pre padding**

**one->Vectors**


**Word embedding technique**

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
sent=['the glass of milk',
      'the glass of jiuce',
      'the cup of tea',
      'im a very good boy',
      'im a good developer',
      'your voice is good']

In [ ]:
sent

['the glass of milk',
 'the glass of jiuce',
 'the cup of tea',
 'im a very good boy',
 'im a good developer',
 'your voice is good']

In [ ]:
voc_size=12000

one hot representation

In [ ]:
onehot_rep=[one_hot(words,voc_size) for words in sent]
print(onehot_rep)

[[2841, 1841, 8419, 11807], [2841, 1841, 8419, 8819], [2841, 1821, 8419, 3837], [6662, 5661, 4855, 7445, 1043], [6662, 5661, 7445, 766], [7372, 526, 11737, 7445]]


Word embedding representation

In [ ]:
from tensorflow.keras.layers import Embedding,InputLayer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
sent_length=8

embedded_docs=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0     0  2841  1841  8419 11807]
 [    0     0     0     0  2841  1841  8419  8819]
 [    0     0     0     0  2841  1821  8419  3837]
 [    0     0     0  6662  5661  4855  7445  1043]
 [    0     0     0     0  6662  5661  7445   766]
 [    0     0     0     0  7372   526 11737  7445]]


Layers

In [ ]:
model=Sequential()
#model.add(InputLayer(input_shape=(8,)))
model.add(Embedding(voc_size,100)) #here it will create voc_size (10000 words) into 10 dimension feature ,10 is feature dimentsion
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_37"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_27 (Embedding)             │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
embedded_docs[0]

array([    0,     0,     0,     0,  2841,  1841,  8419, 11807],
      dtype=int32)

In [ ]:
model.predict(embedded_docs[0])
#print(model.predict(embedded_docs[0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


array([[ 0.01052798,  0.03998382,  0.02989182, -0.04976251, -0.03561706,
         0.00771894, -0.0098043 ,  0.00115646,  0.00974424, -0.04186224,
         0.03127256, -0.00725967,  0.02475167, -0.00443128,  0.04487175,
        -0.04980808, -0.02066877, -0.02025747, -0.03980041,  0.03935001,
        -0.03516967,  0.02345126,  0.01980344,  0.02286004,  0.03465975,
        -0.00796775,  0.01985772,  0.03437686,  0.01085603, -0.02027917,
        -0.03563358, -0.03109795, -0.03492855, -0.02328925, -0.00072337,
         0.01548842, -0.00340339, -0.04397197,  0.03266108, -0.03458118,
         0.01982155, -0.01960804,  0.01993856,  0.01968343, -0.01376684,
        -0.01334804,  0.04045362,  0.01070432,  0.02126181, -0.00936664,
        -0.00813173, -0.02878447, -0.01467289,  0.01150298,  0.02043119,
         0.01072039, -0.04276648, -0.025534  ,  0.00559377,  0.00707084,
        -0.04557167, -0.04729048, -0.03203976,  0.03815868, -0.03317918,
         0.01264742, -0.00514805,  0.03073876,  0.0

Assignment

In [ ]:
sent=['The world is a better place',
      'Marvel series is my favourite movie',
      'I like DC movies',
      'the cat is eating the food',
      'Tom and Jerry is my favourite movie']

In [ ]:
vocabulary_=5000

In [ ]:
#converting words to onehot encoding
onehot_newreq=[one_hot(words,vocabulary_) for words in sent]
print(onehot_newreq)

[[4853, 3698, 4723, 1315, 2315, 3363], [3933, 2295, 4723, 1724, 4581, 1384], [3656, 3308, 3106, 2489], [4853, 845, 4723, 4864, 4853, 2679], [181, 1779, 3604, 4723, 1724, 4581, 1384]]


In [ ]:
#need to do padding to bring in same size
step_size=10
paddingtip=pad_sequences(onehot_newreq,maxlen=step_size,padding='pre')
paddingtip

array([[   0,    0,    0,    0, 4853, 3698, 4723, 1315, 2315, 3363],
       [   0,    0,    0,    0, 3933, 2295, 4723, 1724, 4581, 1384],
       [   0,    0,    0,    0,    0,    0, 3656, 3308, 3106, 2489],
       [   0,    0,    0,    0, 4853,  845, 4723, 4864, 4853, 2679],
       [   0,    0,    0,  181, 1779, 3604, 4723, 1724, 4581, 1384]],
      dtype=int32)

In [ ]:
from tensorflow.keras.layers import Embedding,InputLayer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
model1=Sequential()
model1.add(Embedding(vocabulary_,10))
model1.summary()

Model: "sequential_41"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_31 (Embedding)             │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model1.predict(paddingtip)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step


array([[[-4.7719683e-02, -2.1310044e-02,  4.9234536e-02,  7.8529604e-03,
          3.9941136e-02, -2.7388204e-02, -2.4106419e-02, -2.3182606e-02,
         -6.6084787e-04, -1.4806330e-02],
        [-4.7719683e-02, -2.1310044e-02,  4.9234536e-02,  7.8529604e-03,
          3.9941136e-02, -2.7388204e-02, -2.4106419e-02, -2.3182606e-02,
         -6.6084787e-04, -1.4806330e-02],
        [-4.7719683e-02, -2.1310044e-02,  4.9234536e-02,  7.8529604e-03,
          3.9941136e-02, -2.7388204e-02, -2.4106419e-02, -2.3182606e-02,
         -6.6084787e-04, -1.4806330e-02],
        [-4.7719683e-02, -2.1310044e-02,  4.9234536e-02,  7.8529604e-03,
          3.9941136e-02, -2.7388204e-02, -2.4106419e-02, -2.3182606e-02,
         -6.6084787e-04, -1.4806330e-02],
        [-1.1121333e-02,  2.9290292e-02, -3.4602508e-03,  1.2566235e-02,
          1.6960535e-02, -6.4045079e-03,  9.6742623e-03, -2.8296709e-02,
         -2.5607824e-02, -3.0090107e-02],
        [-3.5502266e-02,  2.2044692e-02, -3.9972864e-02,  1.